import type { Recipe } from "./types"

export const additionalRecipes: Omit<Recipe, "_id">[] = [
  {
    title: "Korean Bibimbap",
    description:
      "A colorful and nutritious Korean rice bowl topped with vegetables, meat, and a spicy gochujang sauce.",
    ingredients: [
      "2 cups cooked short-grain rice",
      "100g beef sirloin, thinly sliced",
      "1 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 tsp sugar",
      "2 cloves garlic, minced",
      "1 cup spinach, blanched",
      "1 carrot, julienned",
      "1 zucchini, julienned",
      "1 cup bean sprouts, blanched",
      "4 shiitake mushrooms, sliced and sautéed",
      "2 eggs, fried sunny-side up",
      "2 tbsp gochujang (Korean chili paste)",
      "1 tbsp honey",
      "1 tbsp rice vinegar",
      "Sesame seeds for garnish",
    ],
    instructions:
      "Marinate the beef: In a bowl, combine the beef with soy sauce, 1 tsp sesame oil, sugar, and garlic. Let it marinate for at least 30 minutes.\n\nPrepare the vegetables: Season the blanched spinach with a pinch of salt and 1 tsp sesame oil. Sauté the julienned carrots and zucchini separately with a pinch of salt until just tender. Season the blanched bean sprouts with a pinch of salt and 1 tsp sesame oil.\n\nCook the beef: Heat a pan over medium-high heat and cook the marinated beef until browned.\n\nPrepare the gochujang sauce: Mix gochujang, honey, rice vinegar, and 1 tbsp sesame oil in a small bowl.\n\nAssemble the bibimbap: Place warm rice in bowls. Arrange the beef and vegetables on top of the rice in separate sections. Place a fried egg in the center of each bowl.\n\nServe with the gochujang sauce on the side or drizzled on top. Sprinkle with sesame seeds before serving.",
    cookingTime: 45,
    servings: 2,
    difficulty: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a29yZWFuJTIwZm9vZHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Dinner",
    cuisine: "Korean",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user1",
        value: 5,
        comment: "Authentic flavors and so colorful! Love the combination of textures.",
        createdAt: new Date(),
      },
      {
        userId: "user2",
        value: 5,
        comment: "This has become a regular in our meal rotation. So delicious!",
        createdAt: new Date(),
      },
    ],
    averageRating: 5.0,
    nutritionalInfo: {
      calories: 550,
      protein: 28,
      carbs: 65,
      fat: 22,
      fiber: 6,
      sugar: 8,
    },
  },
  {
    title: "Greek Moussaka",
    description: "A hearty Greek casserole with layers of eggplant, spiced meat, and creamy béchamel sauce.",
    ingredients: [
      "3 large eggplants, sliced into 1/2 inch rounds",
      "500g ground lamb (or beef)",
      "1 large onion, finely chopped",
      "3 cloves garlic, minced",
      "400g canned tomatoes, crushed",
      "2 tbsp tomato paste",
      "1 cinnamon stick",
      "1 tsp dried oregano",
      "1/2 tsp ground allspice",
      "2 bay leaves",
      "1/4 cup red wine",
      "Salt and pepper to taste",
      "Olive oil for brushing",
      "For the béchamel sauce:",
      "60g butter",
      "60g all-purpose flour",
      "750ml milk, warm",
      "1/4 tsp ground nutmeg",
      "2 eggs, beaten",
      "60g Parmesan cheese, grated",
    ],
    instructions:
      "Prepare the eggplant: Preheat the oven to 400°F (200°C). Brush the eggplant slices with olive oil on both sides, season with salt, and arrange on baking sheets. Bake for 20-25 minutes until soft and golden. Set aside.\n\nMake the meat sauce: Heat 2 tbsp olive oil in a large pan over medium heat. Add the onion and sauté until soft. Add the garlic and cook for another minute. Add the ground meat and cook until browned. Add the tomatoes, tomato paste, cinnamon stick, oregano, allspice, bay leaves, wine, salt, and pepper. Simmer for 30 minutes until the sauce thickens. Remove the cinnamon stick and bay leaves.\n\nMake the béchamel sauce: Melt the butter in a saucepan over medium heat. Add the flour and whisk continuously for 1-2 minutes. Gradually add the warm milk, whisking constantly to prevent lumps. Cook until the sauce thickens. Remove from heat and stir in the nutmeg. Let it cool slightly, then whisk in the beaten eggs and half of the Parmesan cheese.\n\nAssemble the moussaka: Reduce the oven temperature to 350°F (175°C). In a 9x13 inch baking dish, arrange half of the eggplant slices. Spread the meat sauce over the eggplant. Top with the remaining eggplant slices. Pour the béchamel sauce over the top and sprinkle with the remaining Parmesan cheese.\n\nBake for 45-50 minutes until golden brown. Let it rest for 15 minutes before serving.",
    cookingTime: 120,
    servings: 8,
    difficulty: "hard",
    imageUrl:
      "https://images.unsplash.com/photo-1600335895229-6e75511892c8?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z3JlZWslMjBmb29kfGVufDB8fDB8fHww",
    category: "Dinner",
    cuisine: "Greek",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user3",
        value: 5,
        comment: "This moussaka is incredible! Worth the effort.",
        createdAt: new Date(),
      },
      {
        userId: "user4",
        value: 4,
        comment: "Delicious but quite time-consuming. Save it for a weekend project.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.5,
    nutritionalInfo: {
      calories: 420,
      protein: 25,
      carbs: 18,
      fat: 28,
      fiber: 4,
      sugar: 8,
    },
  },
  {
    title: "French Coq au Vin",
    description: "A classic French dish of chicken braised with wine, bacon, mushrooms, and garlic.",
    ingredients: [
      "1 whole chicken (about 1.5kg), cut into 8 pieces",
      "200g bacon or pancetta, diced",
      "24 pearl onions, peeled",
      "300g button mushrooms, quartered",
      "3 cloves garlic, minced",
      "2 tbsp all-purpose flour",
      "750ml red wine (preferably Burgundy)",
      "250ml chicken stock",
      "2 tbsp tomato paste",
      "1 bouquet garni (thyme, parsley, and bay leaf tied together)",
      "3 tbsp butter",
      "2 tbsp olive oil",
      "Salt and freshly ground black pepper",
      "Fresh parsley, chopped, for garnish",
    ],
    instructions:
      "Prepare the chicken: Season the chicken pieces with salt and pepper. In a large Dutch oven, heat 1 tbsp olive oil over medium-high heat. Working in batches, brown the chicken on all sides, about 5-7 minutes per batch. Transfer to a plate.\n\nCook the bacon: In the same pot, add the diced bacon and cook until crispy. Remove with a slotted spoon and set aside, leaving the fat in the pot.\n\nSauté the vegetables: Add the pearl onions to the pot and cook until browned, about 5 minutes. Add the mushrooms and cook until they release their moisture and begin to brown, about 5 more minutes. Add the garlic and cook for 1 minute. Transfer the vegetables to a plate.\n\nMake the sauce: Add 2 tbsp butter to the pot. Once melted, add the flour and cook, stirring constantly, for 1-2 minutes. Slowly whisk in the wine, then add the chicken stock and tomato paste. Bring to a simmer, scraping up any browned bits from the bottom of the pot.\n\nBraise the chicken: Return the chicken, bacon, and any accumulated juices to the pot. Add the bouquet garni, cover, and simmer gently for 25-30 minutes, until the chicken is cooked through.\n\nFinish the dish: Add the reserved vegetables to the pot and simmer for another 10 minutes. Remove the bouquet garni. If the sauce needs thickening, increase the heat and simmer uncovered for a few minutes.\n\nServe: Garnish with fresh parsley and serve with crusty bread or mashed potatoes.",
    cookingTime: 90,
    servings: 6,
    difficulty: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1608855238293-a8853e7f7c98?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8ZnJlbmNoJTIwZm9vZHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Dinner",
    cuisine: "French",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user5",
        value: 5,
        comment: "Absolutely divine! This recipe transported me straight to France.",
        createdAt: new Date(),
      },
      {
        userId: "user6",
        value: 5,
        comment: "The depth of flavor is incredible. My family loved it!",
        createdAt: new Date(),
      },
    ],
    averageRating: 5.0,
    nutritionalInfo: {
      calories: 580,
      protein: 42,
      carbs: 12,
      fat: 32,
      fiber: 2,
      sugar: 4,
    },
  },
  {
    title: "Middle Eastern Falafel with Tahini Sauce",
    description:
      "Crispy chickpea fritters served with a creamy tahini sauce, perfect in a pita or as part of a mezze platter.",
    ingredients: [
      "2 cups dried chickpeas, soaked overnight (do not use canned)",
      "1 small onion, roughly chopped",
      "4 cloves garlic",
      "1 cup fresh parsley leaves",
      "1 cup fresh cilantro leaves",
      "1 tbsp ground cumin",
      "1 tbsp ground coriander",
      "1 tsp cayenne pepper (adjust to taste)",
      "1 tsp baking powder",
      "1 tbsp salt",
      "1/2 tsp black pepper",
      "Vegetable oil for frying",
      "For the tahini sauce:",
      "1/2 cup tahini paste",
      "1/4 cup lemon juice",
      "2 cloves garlic, minced",
      "1/4 cup water (more as needed)",
      "1/4 tsp salt",
      "For serving:",
      "Pita bread",
      "Tomatoes, sliced",
      "Cucumber, sliced",
      "Red onion, thinly sliced",
      "Fresh herbs (parsley, mint)",
      "Pickles",
    ],
    instructions:
      "Prepare the falafel mixture: Drain the soaked chickpeas and pat them dry. Place them in a food processor with the onion, garlic, parsley, cilantro, cumin, coriander, cayenne, salt, and pepper. Pulse until the mixture is finely minced but not pureed, scraping down the sides as necessary.\n\nTransfer the mixture to a bowl, add the baking powder, and mix well. Cover and refrigerate for at least 1 hour or up to overnight.\n\nMake the tahini sauce: In a bowl, whisk together the tahini paste and lemon juice (it will thicken). Add the minced garlic and salt. Gradually add water and whisk until the sauce reaches a smooth, pourable consistency. Adjust seasoning to taste.\n\nForm the falafel: With wet hands, form the mixture into balls or patties about 1.5 inches in diameter.\n\nFry the falafel: Heat 3 inches of oil in a deep pot to 350°F (175°C). Fry the falafel in batches, turning occasionally, until deeply browned and crisp, about 3-4 minutes. Transfer to a paper towel-lined plate to drain.\n\nServe: Serve the falafel hot with tahini sauce, pita bread, and fresh vegetables.",
    cookingTime: 30,
    servings: 6,
    difficulty: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWlkZGxlJTIwZWFzdGVybiUyMGZvb2R8ZW58MHx8MHx8fDA%3D",
    category: "Dinner",
    cuisine: "Middle Eastern",
    dietary: ["vegetarian", "vegan"],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user7",
        value: 5,
        comment: "Best falafel recipe I've tried! So much better than using canned chickpeas.",
        createdAt: new Date(),
      },
      {
        userId: "user8",
        value: 4,
        comment: "Delicious! I baked them instead of frying for a healthier option.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.5,
    nutritionalInfo: {
      calories: 320,
      protein: 12,
      carbs: 35,
      fat: 16,
      fiber: 8,
      sugar: 5,
    },
  },
  {
    title: "Caribbean Jerk Chicken with Rice and Peas",
    description: "Spicy and aromatic Jamaican jerk chicken served with traditional rice and peas.",
    ingredients: [
      "8 chicken thighs, bone-in and skin-on",
      "For the jerk marinade:",
      "4 green onions, roughly chopped",
      "2 Scotch bonnet peppers, seeded (use gloves!)",
      "4 cloves garlic",
      "1 inch piece ginger, peeled",
      "2 tbsp fresh thyme leaves",
      "2 tbsp brown sugar",
      "1 tbsp allspice berries, ground",
      "1 tsp cinnamon",
      "1/2 tsp nutmeg",
      "1 tbsp black peppercorns",
      "2 tbsp soy sauce",
      "2 tbsp lime juice",
      "1/4 cup vegetable oil",
      "For the rice and peas:",
      "2 cups long-grain rice",
      "1 can (400ml) coconut milk",
      "1 can (400g) kidney beans, drained and rinsed",
      "2 cloves garlic, crushed",
      "1 bunch green onions, chopped",
      "1 sprig fresh thyme",
      "1 Scotch bonnet pepper, whole (optional)",
      "1 tsp salt",
    ],
    instructions:
      "Prepare the jerk marinade: Combine all marinade ingredients in a food processor and blend until smooth.\n\nMarinate the chicken: Place the chicken in a large bowl or ziplock bag. Pour the marinade over the chicken, ensuring it's well coated. Cover and refrigerate for at least 4 hours, preferably overnight.\n\nCook the chicken: Preheat grill to medium-high heat. Remove chicken from marinade and grill for 30-35 minutes, turning occasionally, until the chicken is cooked through and the skin is crispy. Alternatively, bake in a 375°F (190°C) oven for 45 minutes.\n\nPrepare the rice and peas: Rinse the rice until the water runs clear. In a large pot, combine the rice, coconut milk, kidney beans, garlic, half of the green onions, thyme, Scotch bonnet (if using), and salt. Add enough water to cover the rice by about 1 inch.\n\nBring to a boil, then reduce heat to low, cover, and simmer for 18-20 minutes until the rice is tender and the liquid is absorbed. Remove the thyme sprig and Scotch bonnet.\n\nServe the jerk chicken with the rice and peas, garnished with the remaining green onions.",
    cookingTime: 60,
    servings: 6,
    difficulty: "medium",
    imageUrl:
      "https://images.unsplash.com/photo-1544378375-c4d3f5d01fb4?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2FyaWJiZWFuJTIwZm9vZHxlbnwwfHwwfHx8MA%3D%3D",
    category: "Dinner",
    cuisine: "Caribbean",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user9",
        value: 5,
        comment: "Authentic flavors! The marinade is perfect.",
        createdAt: new Date(),
      },
      {
        userId: "user10",
        value: 5,
        comment: "This recipe brought me back to Jamaica. Amazing!",
        createdAt: new Date(),
      },
    ],
    averageRating: 5.0,
    nutritionalInfo: {
      calories: 650,
      protein: 35,
      carbs: 45,
      fat: 38,
      fiber: 6,
      sugar: 5,
    },
  },
]
