import type { Recipe } from "./types"

export const sampleRecipes: Omit<Recipe, "_id">[] = [
  {
    title: "Classic Italian Margherita Pizza",
    description: "A traditional Neapolitan pizza with fresh mozzarella, tomatoes, and basil. Simple yet delicious!",
    ingredients: [
      "500g pizza dough",
      "200g San Marzano tomatoes, crushed",
      "250g fresh mozzarella cheese, sliced",
      "Fresh basil leaves",
      "2 tbsp extra virgin olive oil",
      "1 tsp salt",
      "1/2 tsp black pepper",
    ],
    instructions:
      "Preheat your oven to the highest temperature (ideally 500°F/260°C) with a pizza stone or steel if you have one.\n\nStretch or roll out your pizza dough on a floured surface to about 12 inches in diameter.\n\nSpread the crushed tomatoes evenly over the dough, leaving a small border for the crust.\n\nArrange the mozzarella slices evenly over the tomato sauce.\n\nBake for 8-10 minutes until the crust is golden and the cheese is bubbly and slightly browned.\n\nRemove from the oven and immediately top with fresh basil leaves, a drizzle of olive oil, and a sprinkle of salt and pepper.\n\nSlice and serve hot.",
    cookingTime: 15,
    servings: 4,
    difficulty: "easy",
    imageUrl: "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?q=80&w=2069&auto=format&fit=crop",
    category: "Dinner",
    cuisine: "Italian",
    dietary: ["vegetarian"],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user1",
        value: 5,
        comment: "Perfect recipe! The crust came out crispy and the flavors were amazing.",
        createdAt: new Date(),
      },
      {
        userId: "user2",
        value: 4,
        comment: "Delicious and simple. I added some garlic to the olive oil for extra flavor.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.5,
    nutritionalInfo: {
      calories: 320,
      protein: 12,
      carbs: 42,
      fat: 14,
      fiber: 2,
      sugar: 3,
    },
  },
  {
    title: "Spicy Thai Green Curry",
    description: "A fragrant and spicy Thai curry with coconut milk, vegetables, and your choice of protein.",
    ingredients: [
      "2 tbsp green curry paste",
      "400ml coconut milk",
      "500g chicken breast, sliced (or tofu for vegetarian)",
      "1 red bell pepper, sliced",
      "1 zucchini, sliced",
      "100g green beans, trimmed",
      "2 kaffir lime leaves",
      "1 tbsp fish sauce (or soy sauce for vegetarian)",
      "1 tbsp palm sugar or brown sugar",
      "Fresh Thai basil leaves",
      "1 red chili, sliced (optional)",
      "Lime wedges for serving",
    ],
    instructions:
      "Heat a large pan or wok over medium heat. Add a few tablespoons of the thick coconut cream from the top of the coconut milk can and heat until it begins to bubble.\n\nAdd the green curry paste and stir-fry for 1-2 minutes until fragrant.\n\nAdd the chicken (or tofu) and stir-fry until it begins to change color.\n\nPour in the remaining coconut milk, add the kaffir lime leaves, and bring to a gentle simmer.\n\nAdd the bell pepper, zucchini, and green beans. Simmer for 8-10 minutes until the vegetables are tender and the chicken is cooked through.\n\nStir in the fish sauce and palm sugar. Taste and adjust seasonings if needed.\n\nRemove from heat and stir in the Thai basil leaves.\n\nServe hot with steamed jasmine rice, garnished with sliced red chili and lime wedges.",
    cookingTime: 30,
    servings: 4,
    difficulty: "medium",
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?q=80&w=2070&auto=format&fit=crop",
    category: "Dinner",
    cuisine: "Thai",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user3",
        value: 5,
        comment: "Absolutely delicious! Just the right amount of spice.",
        createdAt: new Date(),
      },
      {
        userId: "user4",
        value: 5,
        comment: "Restaurant quality curry at home. Will definitely make again!",
        createdAt: new Date(),
      },
      {
        userId: "user5",
        value: 4,
        comment: "Great recipe, though I added more vegetables.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.7,
    nutritionalInfo: {
      calories: 420,
      protein: 28,
      carbs: 15,
      fat: 30,
      fiber: 3,
      sugar: 6,
    },
  },
  {
    title: "Classic French Croissants",
    description:
      "Buttery, flaky French croissants that are worth the effort. Perfect for a special breakfast or brunch.",
    ingredients: [
      "500g all-purpose flour",
      "10g salt",
      "75g sugar",
      "10g instant yeast",
      "150ml cold water",
      "150ml cold milk",
      "250g cold unsalted butter",
      "1 egg (for egg wash)",
    ],
    instructions:
      "Make the dough: Mix the flour, salt, sugar, and yeast in a large bowl. Add the cold water and milk, and mix until a dough forms. Knead for 3 minutes. Shape into a rectangle, wrap in plastic, and refrigerate for 1 hour.\n\nPrepare the butter: Place the cold butter between two sheets of parchment paper. Using a rolling pin, beat and roll it into a 7x7 inch square. Refrigerate.\n\nLaminate the dough: Roll the chilled dough into an 11x7 inch rectangle. Place the butter square on the bottom two-thirds of the dough. Fold the top third down over the butter, then fold the bottom third up (like a letter). Seal the edges. This is your first turn.\n\nTurn and rest: Rotate the dough 90 degrees. Roll it out to a 14x7 inch rectangle and fold in thirds again. This is your second turn. Wrap and refrigerate for 1 hour.\n\nRepeat the turning process two more times, refrigerating for 1 hour between turns.\n\nAfter the final turn, refrigerate the dough overnight.\n\nShape the croissants: Roll the dough to a 20x12 inch rectangle. Cut into triangles. Roll each triangle from the base to the tip, creating the croissant shape.\n\nProof: Place the shaped croissants on baking sheets, cover, and let rise for 2 hours until puffy.\n\nBake: Preheat oven to 400°F (200°C). Brush croissants with egg wash. Bake for 15-20 minutes until golden brown.",
    cookingTime: 240,
    servings: 12,
    difficulty: "hard",
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=2026&auto=format&fit=crop",
    category: "Breakfast",
    cuisine: "French",
    dietary: ["vegetarian"],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user6",
        value: 5,
        comment: "Time-consuming but absolutely worth it! They taste just like from a French bakery.",
        createdAt: new Date(),
      },
      {
        userId: "user7",
        value: 4,
        comment: "Great recipe but definitely for experienced bakers. Mine turned out delicious but not as pretty.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.5,
    nutritionalInfo: {
      calories: 280,
      protein: 5,
      carbs: 30,
      fat: 16,
      fiber: 1,
      sugar: 8,
    },
  },
  {
    title: "Mexican Street Corn (Elote)",
    description:
      "Grilled corn on the cob slathered with a creamy, spicy sauce and topped with cheese and lime. A popular Mexican street food!",
    ingredients: [
      "6 ears of corn, husked",
      "1/2 cup mayonnaise",
      "1/2 cup sour cream or Mexican crema",
      "1 cup cotija cheese, crumbled (can substitute feta)",
      "2 cloves garlic, minced",
      "1/4 cup fresh cilantro, chopped",
      "2 tsp chili powder",
      "1 tsp lime zest",
      "2 tbsp lime juice",
      "Salt and pepper to taste",
      "Lime wedges for serving",
    ],
    instructions:
      "Preheat grill to medium-high heat.\n\nGrill the corn, turning occasionally, until cooked and lightly charred on all sides, about 8-10 minutes.\n\nWhile the corn is grilling, mix together the mayonnaise, sour cream, minced garlic, lime zest, and lime juice in a bowl.\n\nIn another bowl, combine the cotija cheese, cilantro, and chili powder.\n\nWhen the corn is done, let it cool slightly, then brush each ear generously with the mayonnaise mixture.\n\nRoll the corn in the cheese mixture, coating it evenly.\n\nSprinkle with additional chili powder and cilantro if desired.\n\nServe immediately with lime wedges.",
    cookingTime: 20,
    servings: 6,
    difficulty: "easy",
    imageUrl: "https://images.unsplash.com/photo-1615870216519-2f9fa575fa5c?q=80&w=1964&auto=format&fit=crop",
    category: "Snacks",
    cuisine: "Mexican",
    dietary: ["vegetarian"],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user8",
        value: 5,
        comment: "Amazing! Just like the elote I had in Mexico City.",
        createdAt: new Date(),
      },
      {
        userId: "user9",
        value: 5,
        comment: "Perfect summer side dish. The combination of flavors is incredible!",
        createdAt: new Date(),
      },
      {
        userId: "user10",
        value: 5,
        comment: "So good! I could eat this every day.",
        createdAt: new Date(),
      },
    ],
    averageRating: 5.0,
    nutritionalInfo: {
      calories: 320,
      protein: 8,
      carbs: 25,
      fat: 22,
      fiber: 3,
      sugar: 6,
    },
  },
  {
    title: "Japanese Miso Ramen",
    description: "A comforting bowl of ramen with a rich miso broth, tender pork, and fresh vegetables.",
    ingredients: [
      "4 portions ramen noodles",
      "4 cups chicken stock",
      "3 tbsp white miso paste",
      "1 tbsp soy sauce",
      "1 tbsp sake",
      "1 tbsp mirin",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "300g pork belly, sliced",
      "4 soft-boiled eggs, halved",
      "2 green onions, sliced",
      "1 cup bean sprouts",
      "1 sheet nori, cut into strips",
      "1 tbsp sesame oil",
      "1 tbsp toasted sesame seeds",
    ],
    instructions:
      "Prepare the broth: In a large pot, heat the sesame oil over medium heat. Add the garlic and ginger and sauté until fragrant, about 1 minute.\n\nAdd the chicken stock, miso paste, soy sauce, sake, and mirin. Whisk until the miso is fully dissolved. Simmer for 15 minutes.\n\nMeanwhile, cook the pork belly in a separate pan until crispy on the edges.\n\nCook the ramen noodles according to package instructions, then drain.\n\nAssemble the ramen: Divide the noodles among four bowls. Ladle the hot broth over the noodles.\n\nTop each bowl with sliced pork belly, half a soft-boiled egg, bean sprouts, green onions, and nori strips.\n\nSprinkle with toasted sesame seeds and serve hot.",
    cookingTime: 40,
    servings: 4,
    difficulty: "medium",
    imageUrl: "https://images.unsplash.com/photo-1623341214825-9f4f963727da?q=80&w=2070&auto=format&fit=crop",
    category: "Dinner",
    cuisine: "Japanese",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user11",
        value: 5,
        comment: "Incredible flavor! The broth is so rich and satisfying.",
        createdAt: new Date(),
      },
      {
        userId: "user12",
        value: 4,
        comment: "Delicious! I added some corn and bamboo shoots as well.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.5,
    nutritionalInfo: {
      calories: 550,
      protein: 25,
      carbs: 65,
      fat: 22,
      fiber: 3,
      sugar: 4,
    },
  },
  {
    title: "Indian Butter Chicken (Murgh Makhani)",
    description:
      "Tender chicken in a rich, creamy tomato sauce with aromatic Indian spices. A classic curry that's milder but full of flavor.",
    ingredients: [
      "800g boneless chicken thighs, cut into pieces",
      "2 tbsp lemon juice",
      "2 tsp ground cumin",
      "2 tsp ground coriander",
      "1 tsp turmeric",
      "2 tsp garam masala",
      "2 tsp paprika",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 cup plain yogurt",
      "2 tbsp vegetable oil",
      "1 large onion, finely chopped",
      "2 tbsp butter",
      "1 cinnamon stick",
      "4 cardamom pods",
      "400g canned tomatoes, pureed",
      "1 cup heavy cream",
      "2 tbsp honey",
      "Fresh cilantro for garnish",
      "Naan bread and rice for serving",
    ],
    instructions:
      "Marinate the chicken: In a large bowl, mix the chicken with lemon juice, cumin, coriander, turmeric, 1 tsp garam masala, paprika, half the garlic and ginger, and yogurt. Cover and refrigerate for at least 2 hours, preferably overnight.\n\nCook the chicken: Preheat oven to 400°F (200°C). Place the marinated chicken on a baking sheet and bake for 15 minutes until slightly charred but not fully cooked.\n\nMake the sauce: Heat oil in a large pan over medium heat. Add the onion, cinnamon stick, and cardamom pods. Cook until onion is soft and golden, about 8 minutes.\n\nAdd the remaining garlic and ginger, cook for 1 minute. Add the pureed tomatoes and simmer for 15 minutes until the sauce thickens.\n\nAdd the partially cooked chicken, butter, cream, honey, and remaining garam masala. Simmer for 10-15 minutes until the chicken is fully cooked and the sauce is rich and creamy.\n\nGarnish with fresh cilantro and serve with naan bread and rice.",
    cookingTime: 60,
    servings: 6,
    difficulty: "medium",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=2071&auto=format&fit=crop",
    category: "Dinner",
    cuisine: "Indian",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user13",
        value: 5,
        comment: "Absolutely delicious! The sauce is so rich and flavorful.",
        createdAt: new Date(),
      },
      {
        userId: "user14",
        value: 5,
        comment: "Restaurant quality butter chicken at home. My family loved it!",
        createdAt: new Date(),
      },
      {
        userId: "user15",
        value: 4,
        comment: "Great recipe, though I reduced the cream a bit for a lighter version.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.7,
    nutritionalInfo: {
      calories: 480,
      protein: 32,
      carbs: 18,
      fat: 32,
      fiber: 2,
      sugar: 10,
    },
  },
  {
    title: "Greek Mediterranean Salad",
    description:
      "A refreshing and healthy Greek salad with crisp vegetables, feta cheese, and a simple olive oil dressing.",
    ingredients: [
      "1 large cucumber, diced",
      "4 large tomatoes, diced",
      "1 red onion, thinly sliced",
      "1 green bell pepper, diced",
      "200g feta cheese, cubed",
      "100g kalamata olives",
      "2 tsp dried oregano",
      "1/4 cup extra virgin olive oil",
      "2 tbsp red wine vinegar",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "Fresh mint leaves for garnish (optional)",
    ],
    instructions:
      "In a large bowl, combine the cucumber, tomatoes, red onion, and bell pepper.\n\nAdd the olives and feta cheese to the bowl.\n\nIn a small bowl, whisk together the olive oil, red wine vinegar, dried oregano, salt, and pepper to make the dressing.\n\nPour the dressing over the salad and toss gently to combine.\n\nLet the salad sit for about 10 minutes to allow the flavors to meld.\n\nGarnish with fresh mint leaves if desired and serve.",
    cookingTime: 15,
    servings: 4,
    difficulty: "easy",
    imageUrl: "https://images.unsplash.com/photo-1551248429-40975aa4de74?q=80&w=2090&auto=format&fit=crop",
    category: "Salads",
    cuisine: "Greek",
    dietary: ["vegetarian", "gluten-free"],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user16",
        value: 5,
        comment: "So fresh and delicious! Perfect summer salad.",
        createdAt: new Date(),
      },
      {
        userId: "user17",
        value: 5,
        comment: "Simple but amazing. The dressing is perfect!",
        createdAt: new Date(),
      },
    ],
    averageRating: 5.0,
    nutritionalInfo: {
      calories: 280,
      protein: 8,
      carbs: 12,
      fat: 22,
      fiber: 4,
      sugar: 6,
    },
  },
  {
    title: "American Classic Chocolate Chip Cookies",
    description: "Soft and chewy chocolate chip cookies with crisp edges and melty centers. The perfect sweet treat!",
    ingredients: [
      "225g unsalted butter, softened",
      "200g brown sugar",
      "100g granulated sugar",
      "2 large eggs",
      "2 tsp vanilla extract",
      "280g all-purpose flour",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "300g semi-sweet chocolate chips",
      "100g chopped walnuts (optional)",
    ],
    instructions:
      "Preheat oven to 350°F (175°C) and line baking sheets with parchment paper.\n\nIn a large bowl, cream together the butter, brown sugar, and granulated sugar until light and fluffy, about 3 minutes.\n\nBeat in the eggs one at a time, then stir in the vanilla extract.\n\nIn a separate bowl, whisk together the flour, baking soda, and salt.\n\nGradually add the dry ingredients to the wet ingredients, mixing just until combined.\n\nFold in the chocolate chips and walnuts (if using).\n\nDrop rounded tablespoons of dough onto the prepared baking sheets, spacing them about 2 inches apart.\n\nBake for 10-12 minutes, until the edges are golden but the centers still look slightly underdone.\n\nLet cool on the baking sheets for 5 minutes, then transfer to wire racks to cool completely.",
    cookingTime: 25,
    servings: 24,
    difficulty: "easy",
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?q=80&w=1999&auto=format&fit=crop",
    category: "Desserts",
    cuisine: "American",
    dietary: ["vegetarian"],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user18",
        value: 5,
        comment: "Perfect cookies! Crisp on the outside, chewy in the middle.",
        createdAt: new Date(),
      },
      {
        userId: "user19",
        value: 5,
        comment: "These are dangerous - I can't stop eating them!",
        createdAt: new Date(),
      },
      {
        userId: "user20",
        value: 4,
        comment: "Great recipe. I added some cinnamon for a twist.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.7,
    nutritionalInfo: {
      calories: 220,
      protein: 2,
      carbs: 28,
      fat: 12,
      fiber: 1,
      sugar: 18,
    },
  },
  {
    title: "Vietnamese Pho Bo (Beef Noodle Soup)",
    description: "A fragrant Vietnamese beef noodle soup with a rich broth, rice noodles, and fresh herbs.",
    ingredients: [
      "2kg beef bones (marrow and knuckle bones)",
      "1kg beef brisket",
      "2 onions, halved",
      "4-inch piece of ginger, halved",
      "5 star anise pods",
      "4 cinnamon sticks",
      "6 cloves",
      "1 tbsp coriander seeds",
      "2 tbsp fish sauce",
      "1 tbsp sugar",
      "1 tsp salt",
      "500g rice noodles",
      "200g beef sirloin, thinly sliced",
      "2 cups bean sprouts",
      "1 bunch Thai basil",
      "1 bunch cilantro",
      "2 limes, cut into wedges",
      "2 jalapeños, sliced",
      "Hoisin sauce and sriracha for serving",
    ],
    instructions:
      "Prepare the bones and brisket: Parboil the beef bones and brisket in a large pot of boiling water for 5 minutes. Drain and rinse under cold water.\n\nChar the aromatics: Place the onions and ginger cut-side down on a baking sheet and broil until charred, about 5 minutes.\n\nMake the broth: In a large stockpot, add the bones, brisket, charred onions and ginger, star anise, cinnamon sticks, cloves, and coriander seeds. Cover with 5 liters of water and bring to a boil.\n\nReduce heat to low and simmer for 3 hours, skimming off any foam that rises to the surface.\n\nRemove the brisket after 1.5 hours, let it cool, then slice thinly and set aside.\n\nStrain the broth through a fine-mesh sieve and return to the pot. Add fish sauce, sugar, and salt. Adjust seasonings to taste.\n\nPrepare the noodles according to package instructions.\n\nAssemble the pho: Divide the noodles among bowls. Top with sliced brisket and raw sirloin slices.\n\nLadle the hot broth over the noodles and meat (the hot broth will cook the raw sirloin).\n\nServe with bean sprouts, Thai basil, cilantro, lime wedges, jalapeños, hoisin sauce, and sriracha on the side.",
    cookingTime: 240,
    servings: 6,
    difficulty: "hard",
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?q=80&w=2067&auto=format&fit=crop",
    category: "Dinner",
    cuisine: "Vietnamese",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user21",
        value: 5,
        comment: "Amazing authentic flavor! Worth the time investment.",
        createdAt: new Date(),
      },
      {
        userId: "user22",
        value: 5,
        comment: "This broth is incredible. My family was impressed!",
        createdAt: new Date(),
      },
    ],
    averageRating: 5.0,
    nutritionalInfo: {
      calories: 520,
      protein: 35,
      carbs: 58,
      fat: 16,
      fiber: 3,
      sugar: 4,
    },
  },
  {
    title: "Spanish Seafood Paella",
    description: "A traditional Spanish rice dish loaded with seafood, saffron, and vibrant flavors.",
    ingredients: [
      "300g bomba or arborio rice",
      "1 liter fish stock",
      "1 large pinch saffron threads",
      "3 tbsp olive oil",
      "1 onion, finely chopped",
      "4 cloves garlic, minced",
      "1 red bell pepper, diced",
      "2 tomatoes, diced",
      "1 tsp smoked paprika",
      "200g squid, sliced into rings",
      "12 large shrimp, peeled and deveined",
      "300g mussels, cleaned",
      "200g clams, cleaned",
      "150g firm white fish, cut into chunks",
      "1 cup frozen peas",
      "2 lemons, cut into wedges",
      "Fresh parsley for garnish",
      "Salt and pepper to taste",
    ],
    instructions:
      "Prepare the stock: In a saucepan, warm the fish stock with the saffron threads. Keep it hot but not boiling.\n\nHeat the olive oil in a large paella pan or wide shallow skillet over medium heat. Add the onion and cook until softened, about 5 minutes.\n\nAdd the garlic, bell pepper, and tomatoes. Cook for another 5 minutes until the vegetables are soft.\n\nStir in the smoked paprika and rice, coating the rice with the oil and vegetable mixture.\n\nPour in the hot saffron-infused stock and bring to a simmer. Season with salt and pepper. Do not stir after this point.\n\nCook uncovered for 10 minutes over medium heat.\n\nArrange the seafood on top of the rice: first the squid and fish, then after 5 more minutes, add the shrimp, mussels, and clams.\n\nScatter the peas over the top and continue to cook until the rice is tender and the seafood is cooked through, about 10 more minutes. The mussels and clams should open (discard any that don't).\n\nRemove from heat, cover with a clean kitchen towel, and let rest for 5 minutes.\n\nGarnish with lemon wedges and fresh parsley before serving.",
    cookingTime: 60,
    servings: 6,
    difficulty: "medium",
    imageUrl: "https://images.unsplash.com/photo-1534080564583-6be75777b70a?q=80&w=2070&auto=format&fit=crop",
    category: "Dinner",
    cuisine: "Spanish",
    dietary: [],
    authorId: "system",
    authorName: "RecipeHaven",
    createdAt: new Date(),
    ratings: [
      {
        userId: "user23",
        value: 5,
        comment: "Spectacular! Just like I had in Valencia.",
        createdAt: new Date(),
      },
      {
        userId: "user24",
        value: 4,
        comment: "Delicious but quite a project. Save it for a special occasion.",
        createdAt: new Date(),
      },
    ],
    averageRating: 4.5,
    nutritionalInfo: {
      calories: 490,
      protein: 32,
      carbs: 55,
      fat: 15,
      fiber: 4,
      sugar: 5,
    },
  },
]
